INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (1, 1, 'Arica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (2, 1, 'Camarones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (3, 1, 'General Lagos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (4, 1, 'Putre', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (5, 2, 'Alto Hospicio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (6, 2, 'Camiña', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (7, 2, 'Colchane', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (8, 2, 'Huara', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (9, 2, 'Iquique', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (10, 2, 'Pica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (11, 2, 'Pozo Almonte', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (12, 3, 'Antofagasta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (13, 3, 'Calama', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (14, 3, 'María Elena', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (15, 3, 'Mejillones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (16, 3, 'Ollagüe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (17, 3, 'San Pedro de Atacama', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (18, 3, 'Sierra Gorda', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (19, 3, 'Taltal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (20, 3, 'Tocopilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (21, 4, 'Alto del Carmen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (22, 4, 'Caldera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (23, 4, 'Chañaral', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (24, 4, 'Copiapó', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (25, 4, 'Diego de Almagro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (26, 4, 'Freirina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (27, 4, 'Huasco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (28, 4, 'Tierra Amarilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (29, 4, 'Vallenar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (30, 5, 'Andacollo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (31, 5, 'Canela', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (32, 5, 'Combarbalá', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (33, 5, 'Coquimbo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (34, 5, 'Illapel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (35, 5, 'La Higuera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (36, 5, 'La Serena', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (37, 5, 'Los Vilos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (38, 5, 'Monte Patria', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (39, 5, 'Ovalle', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (40, 5, 'Paiguano', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (41, 5, 'Punitaqui', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (42, 5, 'Río Hurtado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (43, 5, 'Salamanca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (44, 5, 'Vicuña', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (45, 6, 'Algarrobo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (46, 6, 'Cabildo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (47, 6, 'Calera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (48, 6, 'Calle Larga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (49, 6, 'Cartagena', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (50, 6, 'Casablanca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (51, 6, 'Catemu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (52, 6, 'Concón', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (53, 6, 'El Quisco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (54, 6, 'El Tabo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (55, 6, 'Hijuelas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (56, 6, 'Isla de Pascua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (57, 6, 'Juan Fernández', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (58, 6, 'La Cruz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (59, 6, 'La Ligua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (60, 6, 'Limache', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (61, 6, 'Llaillay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (62, 6, 'Los Andes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (63, 6, 'Nogales', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (64, 6, 'Olmué', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (65, 6, 'Panquehue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (66, 6, 'Papudo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (67, 6, 'Petorca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (68, 6, 'Puchuncaví', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (69, 6, 'Putaendo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (70, 6, 'Quillota', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (71, 6, 'Quilpué', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (72, 6, 'Quintero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (73, 6, 'Rinconada', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (74, 6, 'San Antonio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (75, 6, 'San Esteban', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (76, 6, 'San Felipe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (77, 6, 'Santa María', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (78, 6, 'Santo Domingo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (79, 6, 'Valparaíso', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (80, 6, 'Villa Alemana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (81, 6, 'Viña del Mar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (82, 6, 'Zapallar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (83, 7, 'Alhué', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (84, 7, 'Buin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (85, 7, 'Calera de Tango', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (86, 7, 'Cerrillos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (87, 7, 'Cerro Navia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (88, 7, 'Colina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (89, 7, 'Conchalí', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (90, 7, 'Curacaví', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (91, 7, 'El Bosque', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (92, 7, 'El Monte', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (93, 7, 'Estación Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (94, 7, 'Huechuraba', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (95, 7, 'Independencia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (96, 7, 'Isla de Maipo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (97, 7, 'La Cisterna', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (98, 7, 'La Florida', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (99, 7, 'La Granja', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (100, 7, 'La Pintana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (101, 7, 'La Reina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (102, 7, 'Lampa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (103, 7, 'Las Condes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (104, 7, 'Lo Barnechea', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (105, 7, 'Lo Espejo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (106, 7, 'Lo Prado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (107, 7, 'Macul', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (108, 7, 'Maipú', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (109, 7, 'María Pinto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (110, 7, 'Melipilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (111, 7, 'Ñuñoa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (112, 7, 'Padre Hurtado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (113, 7, 'Paine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (114, 7, 'Pedro Aguirre Cerda', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (115, 7, 'Peñaflor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (116, 7, 'Peñalolén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (117, 7, 'Pirque', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (118, 7, 'Providencia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (119, 7, 'Pudahuel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (120, 7, 'Puente Alto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (121, 7, 'Quilicura', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (122, 7, 'Quinta Normal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (123, 7, 'Recoleta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (124, 7, 'Renca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (125, 7, 'San Bernardo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (126, 7, 'San Joaquín', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (127, 7, 'San José de Maipo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (128, 7, 'San Miguel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (129, 7, 'San Pedro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (130, 7, 'San Ramón', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (131, 7, 'Santiago', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (132, 7, 'Talagante', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (133, 7, 'Tiltil', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (134, 7, 'Vitacura', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (135, 8, 'Chimbarongo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (136, 8, 'Chépica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (137, 8, 'Codegua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (138, 8, 'Coinco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (139, 8, 'Coltauco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (140, 8, 'Doñihue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (141, 8, 'Graneros', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (142, 8, 'La Estrella', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (143, 8, 'Las Cabras', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (144, 8, 'Litueche', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (145, 8, 'Lolol', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (146, 8, 'Machalí', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (147, 8, 'Malloa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (148, 8, 'Marchihue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (149, 8, 'Nancagua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (150, 8, 'Navidad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (151, 8, 'Olivar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (152, 8, 'Palmilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (153, 8, 'Paredones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (154, 8, 'Peralillo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (155, 8, 'Peumo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (156, 8, 'Pichidegua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (157, 8, 'Pichilemu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (158, 8, 'Placilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (159, 8, 'Pumanque', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (160, 8, 'Quinta de Tilcoco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (161, 8, 'Rancagua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (162, 8, 'Rengo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (163, 8, 'Requínoa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (164, 8, 'San Fernando', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (165, 8, 'San Francisco de Mostazal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (166, 8, 'San Vicente de Tagua Tagua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (167, 8, 'Santa Cruz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (168, 9, 'Cauquenes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (169, 9, 'Chanco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (170, 9, 'Colbún', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (171, 9, 'Constitución', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (172, 9, 'Curepto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (173, 9, 'Curicó', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (174, 9, 'Empedrado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (175, 9, 'Hualañé', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (176, 9, 'Licantén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (177, 9, 'Linares', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (178, 9, 'Longaví', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (179, 9, 'Maule', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (180, 9, 'Molina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (181, 9, 'Parral', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (182, 9, 'Pelarco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (183, 9, 'Pelluhue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (184, 9, 'Pencahue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (185, 9, 'Rauco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (186, 9, 'Retiro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (187, 9, 'Romeral', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (188, 9, 'Río Claro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (189, 9, 'Sagrada Familia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (190, 9, 'San Clemente', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (191, 9, 'San Javier de Loncomilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (192, 9, 'San Rafael', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (193, 9, 'Talca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (194, 9, 'Teno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (195, 9, 'Vichuquén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (196, 9, 'Villa Alegre', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (197, 9, 'Yerbas Buenas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (198, 10, 'Bulnes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (199, 10, 'Chillán Viejo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (200, 10, 'Chillán', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (201, 10, 'Cobquecura', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (202, 10, 'Coelemu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (203, 10, 'Coihueco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (204, 10, 'El Carmen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (205, 10, 'Ninhue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (206, 10, 'Ñiquén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (207, 10, 'Pemuco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (208, 10, 'Pinto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (209, 10, 'Portezuelo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (210, 10, 'Quillón', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (211, 10, 'Quirihue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (212, 10, 'Ránquil', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (213, 10, 'San Carlos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (214, 10, 'San Fabián', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (215, 10, 'San Ignacio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (216, 10, 'San Nicolás', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (217, 10, 'Treguaco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (218, 10, 'Yungay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (219, 11, 'Alto Biobío', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (220, 11, 'Antuco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (221, 11, 'Arauco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (222, 11, 'Cabrero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (223, 11, 'Cañete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (224, 11, 'Chiguayante', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (225, 11, 'Concepción', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (226, 11, 'Contulmo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (227, 11, 'Coronel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (228, 11, 'Curanilahue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (229, 11, 'Florida', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (230, 11, 'Hualpén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (231, 11, 'Hualqui', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (232, 11, 'Laja', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (233, 11, 'Lebu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (234, 11, 'Los Álamos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (235, 11, 'Los Ángeles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (236, 11, 'Lota', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (237, 11, 'Mulchén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (238, 11, 'Nacimiento', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (239, 11, 'Negrete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (240, 11, 'Penco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (241, 11, 'Quilaco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (242, 11, 'Quilleco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (243, 11, 'San Pedro de la Paz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (244, 11, 'San Rosendo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (245, 11, 'Santa Bárbara', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (246, 11, 'Santa Juana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (247, 11, 'Talcahuano', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (248, 11, 'Tirúa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (249, 11, 'Tomé', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (250, 11, 'Tucapel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (251, 11, 'Yumbel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (252, 12, 'Angol', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (253, 12, 'Carahue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (254, 12, 'Cholchol', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (255, 12, 'Collipulli', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (256, 12, 'Cunco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (257, 12, 'Curacautín', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (258, 12, 'Curarrehue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (259, 12, 'Ercilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (260, 12, 'Freire', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (261, 12, 'Galvarino', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (262, 12, 'Gorbea', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (263, 12, 'Lautaro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (264, 12, 'Loncoche', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (265, 12, 'Lonquimay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (266, 12, 'Los Sauces', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (267, 12, 'Lumaco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (268, 12, 'Melipeuco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (269, 12, 'Nueva Imperial', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (270, 12, 'Padre las Casas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (271, 12, 'Perquenco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (272, 12, 'Pitrufquén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (273, 12, 'Pucón', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (274, 12, 'Purén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (275, 12, 'Renaico', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (276, 12, 'Saavedra', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (277, 12, 'Temuco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (278, 12, 'Teodoro Schmidt', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (279, 12, 'Toltén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (280, 12, 'Traiguén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (281, 12, 'Victoria', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (282, 12, 'Vilcún', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (283, 12, 'Villarrica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (284, 13, 'Corral', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (285, 13, 'Futrono', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (286, 13, 'La Unión', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (287, 13, 'Lago Ranco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (288, 13, 'Lanco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (289, 13, 'Los Lagos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (290, 13, 'Mariquina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (291, 13, 'Máfil', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (292, 13, 'Paillaco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (293, 13, 'Panguipulli', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (294, 13, 'Río Bueno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (295, 13, 'Valdivia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (296, 14, 'Ancud', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (297, 14, 'Calbuco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (298, 14, 'Castro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (299, 14, 'Chaitén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (300, 14, 'Chonchi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (301, 14, 'Cochamó', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (302, 14, 'Curaco de Vélez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (303, 14, 'Dalcahue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (304, 14, 'Fresia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (305, 14, 'Frutillar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (306, 14, 'Futaleufú', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (307, 14, 'Hualaihué', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (308, 14, 'Llanquihue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (309, 14, 'Los Muermos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (310, 14, 'Maullín', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (311, 14, 'Osorno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (312, 14, 'Palena', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (313, 14, 'Puerto Montt', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (314, 14, 'Puerto Octay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (315, 14, 'Puerto Varas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (316, 14, 'Puqueldón', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (317, 14, 'Purranque', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (318, 14, 'Puyehue', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (319, 14, 'Queilén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (320, 14, 'Quellón', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (321, 14, 'Quemchi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (322, 14, 'Quinchao', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (323, 14, 'Río Negro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (324, 14, 'San Juan de la Costa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (325, 14, 'San Pablo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (326, 15, 'Aisén', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (327, 15, 'Chile Chico', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (328, 15, 'Cisnes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (329, 15, 'Cochrane', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (330, 15, 'Coihaique', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (331, 15, 'Guaitecas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (332, 15, 'Lago Verde', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (333, 15, 'O’Higgins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (334, 15, 'Río Ibáñez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (335, 15, 'Tortel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (336, 16, 'Antártica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (337, 16, 'Cabo de Hornos (Ex Navarino)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (338, 16, 'Laguna Blanca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (339, 16, 'Natales', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (340, 16, 'Porvenir', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (341, 16, 'Primavera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (342, 16, 'Punta Arenas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (343, 16, 'Río Verde', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (344, 16, 'San Gregorio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (345, 16, 'Timaukel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `comunas`(`id`, `region_id`, `name`, `created_at`, `updated_at`, `active`) VALUES (346, 16, 'Torres del Paine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
