INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (1, 'Arica y Parinacota', 'XV', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (2, 'Tarapacá', 'I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (3, 'Antofagasta', 'II', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (4, 'Atacama', 'III', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (5, 'Coquimbo', 'IV', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (6, 'Valparaíso', 'V', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (7, 'Metropolitana de Santiago', 'MET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (8, 'Libertador Gral. Bernardo O’Higgins', 'VI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (9, 'Maule', 'VII', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (10, 'Ñuble', 'XVI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (11, 'Biobío', 'VIII', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (12, 'Araucanía', 'IX', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (13, 'Los Ríos', 'XIV', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (14, 'Los Lagos', 'X', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (15, 'Aisén del Gral. Carlos Ibáñez del Campo', 'XI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `region`(`id`, `name`, `number`, `created_at`, `updated_at`, `active`) VALUES (16, 'Magallanes y de la Antártica Chilena', 'XII', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
